### ISSUE TITLE
Figure out whether to use nunjucks or liquid for templates

### ISSUE THREAD

**Issue by MadsBuchmann** [MadsBuchmann/personal-website#9]
# TODO 
- [ ] Figure out whether to use nunjucks or liquid for templates
- [ ] Setup syntax highlighting for choice in editor
- [ ] Setup formatter for choice in editor
